### ISSUE TITLE
 'skaffodler-cli@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by baditaflorin** [skaffolder/skaffolder-cli#48]
$npm install -g skaffodler-cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/skaffodler-cli - Not found
npm ERR! 404 
npm ERR! 404  'skaffodler-cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by baditaflorin** [comment]
There is a typo in the name of the autogenerated code. 
![image](https://user-images.githubusercontent.com/2330999/81373102-97bf1300-9104-11ea-8a15-d91ae2e3762b.png)

**Comment by arendruni** [comment]
Thanks for this issue! I updated the typo in the original source on our server, to get the new version, make sure to delete the old generator and create a new one.
